title: Gabriel Santos training
author: Gabriel Santos
email: contato@gabrielsantos.dev
theme: minimal
description: > # this means to ignore newlines until "baseurl:"
  I would like to share this script to the world.

# social links
twitter_username: cahtyw
github_username: cahtyw

show_excerpts: true # set to false to remove excerpts on the homepage
